### ISSUE TITLE
Error- Unsupported operand types - IFM .exe

### ISSUE THREAD

**Issue by Petr446** [Soramuse/IFM-Calculator#2]
Hello, 

I have an issue with loading the data to IFM. Can you please provide me with support regarding this error?
I have not found out the reason for this issue.
![WhatsApp Image 2024-06-05 at 09 00 58_f1c2d19e](https://github.com/Soramuse/IFM-Calculator/assets/171907291/267eeafa-8880-47a4-8bff-328ba5812ed0)
![WhatsApp Image 2024-06-05 at 09 01 39_2375b9de](https://github.com/Soramuse/IFM-Calculator/assets/171907291/c3817a44-4b39-48a6-9426-01bce125c880)

Thank you in advance.

Petr

**Comment by Soramuse** [comment]
Hey, Petr, I'm glad you provided me with feedback. I was quite busy recently, which is why I didn't get back to you earlier. The error seems to stem from a situation where the software is attempting to subtract one string from another during the calculation process. This is not typical and should not occur, as 'data' should consist of numerical values. I recommend checking the data within 'data_series' for any errors, such as ensuring there are no separators within the numbers. Please ensure that the data consists of pure numerical values and verify the data format.

**Comment by Petr446** [comment]
Hello @Soramuse ,

I hope you are doing great! Thank you for your answer. I have checked the data and adjusted them.

But now, I am facing a new error. I believe that I have correctly named the columns. 
 
![aaa](https://github.com/Soramuse/IFM-Calculator/assets/171907291/fb18e537-5ffd-4132-891f-23bf9e29c887)
![bbb](https://github.com/Soramuse/IFM-Calculator/assets/171907291/71194e33-3552-492c-a433-8eae335425df)

Can you please share with me any advice?

I look forward to hearing from you soon.

Petr

**Comment by Soramuse** [comment]
You should use commas (,) instead of semicolons (;) to separate the data. You can use Excel to open the CSV file to confirm its correctness.

Jun

**Comment by Petr446** [comment]
Hello Jun, @Soramuse 

Thank you for the advice, it worked. Unfortunately, I have one more error.
![ccc](https://github.com/Soramuse/IFM-Calculator/assets/171907291/7964c579-9496-4188-b67e-465df27f6b99)
Sorry for disturbing you so much from your work.

Petr

**Comment by Petr446** [comment]
Dear Jun, @Soramuse 


Thank you very much. I have solved it. I had also replace the the "," by "." and than replace ";" by ","..

Have a nice day!

Petr

**Comment by Soramuse** [comment]
Glad to help you out. I hope IFM-Cal can be useful to your work. Feel free to ask me if you have any questions.

Jun

**Comment by Petr446** [comment]
Dear Jun,

Thank you! I have 4 different variants, that I would like to use for evaluation. Is there any possibility of adjusting the scale in the "figure" interface? To have only one scale for all 4 models?

I look forward to hearing from you soon.

Petr

**Comment by Soramuse** [comment]
If you simply want to zoom in on the figure, you can use the scroll wheel on your mouse to zoom. If you wish to adjust the scale, I'm sorry, but that functionality isn't available at the moment. The scale is currently automatically estimated based on the maximum and minimum values. 

In the future, I plan to reconstruct the visualization part using VTK instead of the current matplotlib. At that time, there will be more customizable options available, and I will incorporate your ideas then.

Jun
